### ISSUE TITLE
Formatting fails on Julia 1.6

### ISSUE THREAD

**Issue by jagot** [ronisbr/PrettyTables.jl#99] opened 2020-12-01 13:49 UTC
This simple example works fine on Julia 1.5, but fails on Julia 1.6:
```julia
using PrettyTables

data = [0.0533803  0.0144148
         10.7327     2.89827
        23.9991     6.48073]
pretty_table(data, formatters = ft_printf("%5.3f"))
```
TOMLs attached: [tomls.zip](https://github.com/ronisbr/PrettyTables.jl/files/5622975/tomls.zip)

# Julia 1.5
```
┌────────┬────────┐
│ Col. 1 │ Col. 2 │
├────────┼────────┤
│  0.053 │  0.014 │
│ 10.733 │  2.898 │
│ 23.999 │  6.481 │
└────────┴────────┘
```
# Julia 1.6
```
ERROR: LoadError: MethodError: no method matching parse(::String)
Closest candidates are:
  parse(::Type{Sockets.IPAddr}, ::AbstractString) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Sockets/src/IPAddr.jl:246
  parse(::Type{T}, ::AbstractChar; base) where T<:Integer at parse.jl:40
  parse(::Type{T}, ::AbstractString; base) where T<:Integer at parse.jl:240
  ...
Stacktrace:
  [1] checkfmt(fmt::String)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/cformat.jl:6
  [2] generate_formatter(fmt::String)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/cformat.jl:17
  [3] sprintf1(fmt::String, x::Float64)
    @ Formatting ~/.julia/packages/Formatting/LU9hd/src/cformat.jl:3
  [4] #30
    @ ~/.julia/packages/PrettyTables/W16qB/src/predefined_formatters.jl:47 [inlined]
  [5] _fill_matrix_data!(header_str::Matrix{String}, header_len::Matrix{Int64}, data_str::Matrix{Vector{String}}, data_len::Matrix{Vector{Int64}}, cols_width::Vector{Int64}, id_cols::Vector{Int64}, id_rows::Vector{Int64}, num_lines_in_row::Vector{Int64}, jvec::Vector{Int64}, jrvec::Vector{Int64}, Δc::Int64, columns_width::Vector{Int64}, data::Matrix{Float64}, header::Vector{String}, formatters::Tuple{PrettyTables.var"#30#32"{Vector{String}}}, display::PrettyTables.Display, autowrap::Bool, cell_first_line_only::Bool, compact_printing::Bool, crop_subheader::Bool, fixed_col_width::Vector{Bool}, linebreaks::Bool, maximum_columns_width::Vector{Int64}, noheader::Bool, renderer::Val{:print}, vcrop_mode::Symbol)
    @ PrettyTables ~/.julia/packages/PrettyTables/W16qB/src/backends/text/fill.jl:160
  [6] _pt_text(io::IOContext{Base.TTY}, pinfo::PrettyTables.PrintInfo; border_crayon::Crayon, header_crayon::Crayon, subheader_crayon::Crayon, rownum_header_crayon::Crayon, text_crayon::Crayon, omitted_cell_summary_crayon::Crayon, autowrap::Bool, body_hlines::Vector{Int64}, body_hlines_format::Nothing, continuation_row_alignment::Symbol, crop::Symbol, crop_subheader::Bool, crop_num_lines_at_beginning::Int64, columns_width::Int64, display_size::Tuple{Int64, Int64}, equal_columns_width::Bool, ellipsis_line_skip::Int64, highlighters::Tuple{}, hlines::Nothing, linebreaks::Bool, maximum_columns_width::Int64, minimum_columns_width::Int64, newline_at_end::Bool, overwrite::Bool, noheader::Bool, nosubheader::Bool, row_name_crayon::Crayon, row_name_header_crayon::Crayon, row_number_alignment::Symbol, show_omitted_cell_summary::Bool, sortkeys::Bool, tf::TextFormat, title_autowrap::Bool, title_crayon::Crayon, title_same_width_as_table::Bool, vcrop_mode::Symbol, vlines::Nothing)
    @ PrettyTables ~/.julia/packages/PrettyTables/W16qB/src/backends/text/print.jl:278
  [7] _pt_text(io::IOContext{Base.TTY}, pinfo::PrettyTables.PrintInfo)
    @ PrettyTables ~/.julia/packages/PrettyTables/W16qB/src/backends/text/print.jl:50
  [8] #_pt#68
    @ ~/.julia/packages/PrettyTables/W16qB/src/private.jl:422 [inlined]
  [9] #_pretty_table#67
    @ ~/.julia/packages/PrettyTables/W16qB/src/private.jl:356 [inlined]
 [10] #pretty_table#46
    @ ~/.julia/packages/PrettyTables/W16qB/src/print.jl:670 [inlined]
 [11] top-level scope
    @ /tmp/test-table.jl:6
 [12] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [13] top-level scope
    @ REPL[3]:1
```

**Comment by ronisbr** [comment] 2020-12-01 14:15
Hi @jagot 

Unfortunately this is outside this package. The problem is in [Formatting.jl](https://github.com/JuliaIO/Formatting.jl). The issue was already fixed on `master`, but they must release a new version. I already opened a bug to ask for it: https://github.com/JuliaIO/Formatting.jl/issues/94

**Closed** 2020-12-01 14:15 UTC
