### ISSUE TITLE
error at using headers in Julia V1.6

### ISSUE THREAD

**Issue by carlomontec** [ronisbr/PrettyTables.jl#117] opened 2021-04-15 17:24 UTC
The examples of the documentation for using headers fail under Julia 1.6.0 and   [08abe8d2] PrettyTables v0.11.1
```

`   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> using PrettyTables

julia> data = [1 2 3; 4 5 6];

julia> pretty_table(data; header = ["Column 1", "Column 2", "Column 3"])
ERROR: MethodError: no method matching _pt_text(::IOContext{Base.TTY}, ::PrettyTables.PrintInfo; header=["Column 1", "Column 2", "Column 3"])
Closest candidates are:
  _pt_text(::IO, ::PrettyTables.PrintInfo; border_crayon, header_crayon, subheader_crayon, rownum_header_crayon, text_crayon, omitted_cell_summary_crayon, alignment_anchor_fallback, alignment_anchor_fallback_override, T, T, alignment_anchor_regex, autowrap, body_hlines, body_hlines_format, continuation_row_alignment, crop, crop_subheader, crop_num_lines_at_beginning, columns_width, display_size, equal_columns_width, ellipsis_line_skip, highlighters, hlines, linebreaks, maximum_columns_width, minimum_columns_width, newline_at_end, overwrite, noheader, nosubheader, row_name_crayon, row_name_header_crayon, row_number_alignment, show_omitted_cell_summary, sortkeys, tf, title_autowrap, title_crayon, title_same_width_as_table, vcrop_mode, vlines) at /home/carlo/.julia/packages/PrettyTables/ayuQh/src/backends/text/print.jl:10 got unsupported keyword argument "header"

`
```

Furthermore, thank you for this wonderful package!

**Comment by ronisbr** [comment] 2021-04-15 17:33
Hi @carlomontec !

Are you sure that you are using the latest version of PrettyTables? Is it possible to get the result of `]st`?

> Furthermore, thank you for this wonderful package!

Nice! I am glad it is being useful :)

**Comment by lmiq** [comment] 2021-04-16 13:42
I have the same error, and PrettyTables is at version 0.11.1. But it does not update to 0.12 for some unknown reason. There might some package preventing from update?

**Comment by carlomontec** [comment] 2021-04-16 14:06
>  Is it possible to get the result of `]st`?

Sure:


```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb* (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 24

(@v1.6) pkg> update
    Updating registry at `~/.julia/registries/General`
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [7d9fca2a] Arpack v0.5.2
  [336ed68f] CSV v0.8.4
  [717857b8] DSP v0.6.10
  [a93c6f00] DataFrames v0.22.7
  [5789e2e9] FileIO v1.6.5
  [c91e804a] Gadfly v1.3.2
  [916415d5] Images v0.24.0
  [033835bb] JLD2 v0.4.3
  [682c06a0] JSON v0.21.1
  [23992714] MAT v0.10.1
  [0c723cd3] MKLSparse v1.1.0
  [6fafb56a] Memoization v0.1.5
  [6fd5a793] Octavian v0.2.13
  [5fb14364] OhMyREPL v0.5.10
  [46dd5b70] Pardiso v0.5.1
  [ccf2f8ad] PlotThemes v2.0.1
  [f0f68f2c] PlotlyJS v0.14.1
  [91a5bcdd] Plots v1.11.2
  [08abe8d2] PrettyTables v0.11.1
  [92933f4c] ProgressMeter v1.5.0
  [6038ab10] Rotations v1.0.2
  [af85af4c] RowEchelon v0.2.1
  [b8865327] UnicodePlots v1.3.0
  [64499a7a] WriteVTK v1.9.2
  [ade2ca70] Dates
  [8bb1440f] DelimitedFiles
  [37e2e46d] LinearAlgebra
  [de0858da] Printf
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [fa267f1f] TOML


julia> using PrettyTables

julia> data = [1 2 3; 4 5 6];

julia> pretty_table(data; header = ["Column 1", "Column 2", "Column 3"])
ERROR: MethodError: no method matching _pt_text(::IOContext{Base.TTY}, ::PrettyTables.PrintInfo; header=["Column 1", "Column 2", "Column 3"])
Closest candidates are:
  _pt_text(::IO, ::PrettyTables.PrintInfo; border_crayon, header_crayon, subheader_crayon, rownum_header_crayon, text_crayon, omitted_cell_summary_crayon, alignment_anchor_fallback, alignment_anchor_fallback_override, T, T, alignment_anchor_regex, autowrap, body_hlines, body_hlines_format, continuation_row_alignment, crop, crop_subheader, crop_num_lines_at_beginning, columns_width, display_size, equal_columns_width, ellipsis_line_skip, highlighters, hlines, linebreaks, maximum_columns_width, minimum_columns_width, newline_at_end, overwrite, noheader, nosubheader, row_name_crayon, row_name_header_crayon, row_number_alignment, show_omitted_cell_summary, sortkeys, tf, title_autowrap, title_crayon, title_same_width_as_table, vcrop_mode, vlines) at /home/carlo/.julia/packages/PrettyTables/ayuQh/src/backends/text/print.jl:10 got unsupported keyword argument "header"
Stacktrace:
 [1] kwerr(::NamedTuple{(:header,), Tuple{Vector{String}}}, ::Function, ::IOContext{Base.TTY}, ::PrettyTables.PrintInfo)
   @ Base ./error.jl:157
 [2] _pt(io::IOContext{Base.TTY}, data::Matrix{Int64}, header::Vector{String}; alignment::Symbol, backend::Nothing, cell_alignment::Nothing, cell_first_line_only::Bool, compact_printing::Bool, filters_row::Nothing, filters_col::Nothing, formatters::Nothing, header_alignment::Symbol, header_cell_alignment::Nothing, limit_printing::Bool, renderer::Symbol, row_names::Nothing, row_name_alignment::Symbol, row_name_column_title::String, row_number_column_title::String, show_row_number::Bool, title::String, title_alignment::Symbol, kwargs::Base.Iterators.Pairs{Symbol, Vector{String}, Tuple{Symbol}, NamedTuple{(:header,), Tuple{Vector{String}}}})
   @ PrettyTables ~/.julia/packages/PrettyTables/ayuQh/src/private.jl:425
 [3] _pretty_table(io::IOContext{Base.TTY}, data::Matrix{Int64}, header::Vector{String}; kwargs::Base.Iterators.Pairs{Symbol, Vector{String}, Tuple{Symbol}, NamedTuple{(:header,), Tuple{Vector{String}}}})
   @ PrettyTables ~/.julia/packages/PrettyTables/ayuQh/src/private.jl:357
 [4] #pretty_table#46
   @ ~/.julia/packages/PrettyTables/ayuQh/src/print.jl:718 [inlined]
 [5] top-level scope
   @ REPL[16]:1
```

**Comment by lmiq** [comment] 2021-04-16 14:08
```
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [6e4b80f9] BenchmarkTools v0.6.0
  [336ed68f] CSV v0.8.4
  [b630d9fa] CheapThreads v0.1.10
  [35d6a980] ColorSchemes v3.11.0
  [6f35c628] ComplexMixtures v0.4.13
  [a93c6f00] DataFrames v0.22.6
  [fde71243] EasyFit v0.5.4
  [7a1cc6ca] FFTW v1.3.2
  [59287772] Formatting v0.4.2
  [f67ccb44] HDF5 v0.15.4
  [7073ff75] IJulia v1.23.2
  [18364772] IPython v0.5.0
  [b964fa9f] LaTeXStrings v1.2.1
  [bdcacae8] LoopVectorization v0.12.11
  [33e6dc65] MKL v0.4.0
  [6741aa20] Neptune v0.14.0
  [6fd5a793] Octavian v0.2.12
  [429524aa] Optim v1.3.0
  [e29189f1] PDBTools v0.11.1
  [8314cec4] PGFPlotsX v1.2.10
  [91a5bcdd] Plots v1.7.3
  [c3e4b0f8] Pluto v0.14.1
  [7f904dfe] PlutoUI v0.7.1
  [08abe8d2] PrettyTables v0.11.1
  [295af30f] Revise v3.1.6
  [efcf1570] Setfield v0.7.0
  [aa65fe97] SnoopCompile v2.1.2
  [e2b509da] SnoopCompileCore v2.1.2
  [860ef19b] StableRNGs v1.0.0
  [90137ffa] StaticArrays v0.12.5
  [0c5d862f] Symbolics v0.1.18
  [a759f4b9] TimerOutputs v0.5.8
  [bc48ee85] Tullio v0.2.13
  [33b4df10] VectorizedRNG v0.2.8
  [de0858da] Printf


```

**Comment by ronisbr** [comment] 2021-04-16 14:17
Yes, this API modification was implemented at v0.12. You could not update to PrettyTables.jl because of DataFrames.jl. The version that supports PrettyTables v0.12 is not released yet. Thus, Pkg.jl keeps PrettyTables.jl at version v0.11.

**Comment by ronisbr** [comment] 2021-04-16 14:17
The only option to use PrettyTables.jl v0.12 and DataFrames.jl is to use DataFrames.jl `main` branch instead of the released version.

**Comment by lmiq** [comment] 2021-04-16 14:19
Obrigado. Posso esperar :-)

**Comment by ronisbr** [comment] 2021-04-17 02:53
I will close this bug since it seems to be related only to this block caused by DataFrames. Feel free to open it again if necessary!

**Closed by ronisbr** 2021-04-17 02:53 UTC
